services:
  - type: web
    name: chugli-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    healthCheckPath: /api/auth/check
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://chugli.jayvarma.site
      - key: EMAIL_FROM_NAME
        value: Chugli
      - key: ARCJET_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_PASSWORD_RESET_TEMPLATE_ID
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ARCJET_KEY
        sync: false


