services:
  - type: web
    name: chugli-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: MONGO_URI
        fromDatabase:
          name: chugli-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://chugli.jayvarma.site
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: Chugli
      - key: RESEND_PASSWORD_RESET_TEMPLATE_ID
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: ARCJET_ENV
        value: production
    rootDir: backend
    healthCheckPath: /api/auth/check
    headers:
      - http:
          paths:
            - path: /socket.io
              methods:
                - GET
                - POST
              cacheControl: no-cache

databases:
  - name: chugli-db
    engine: mongodb
    plan: free
